### ISSUE TITLE
Deprecated each

### ISSUE THREAD

**Issue by maferblancor** [bseddon/php-pivottables-4-excel-lite#1]
I'm trying to run the library with Laravel 5.7 with Php7.

And always getting the same error with almost all of the new classes:

each method its deprecated. 

I change each while(list) each I found
for 
foreach($somegroup as $key=>$var)

and now I'm getting empty arrays. 

Could you help me, please?

**Comment by maferblancor** [comment]
Ok, it works! 
But i have to change the while in almost all of the new classes. Thanks. 

```
foreach ($this->pivotCacheDefinitions as $key=>$val){
	yield $key => $val;
}
/* 
while(list($key, $val) = each($this->pivotCacheDefinitions))
{
		yield $key => $val;
}
 */
```

**Comment by bseddon** [comment]
Hi

It's great that you have it working and thanks for the suggested change.  A lot of the code in the 'new' classes is copied over from the originals because the package is not extendable in the way needed for the pivot table features.  I imagine that if you look in the original classes they will include the 'while' structure.

I will apply the change to the code so everyone else can benefit from your excellent suggestion!

Thanks

**Comment by bseddon** [comment]
No! I added the 'while' construct.  What was I thinking!?!
